### ISSUE TITLE
FirmwareImageDetailView raised exception during schema generation

### ISSUE THREAD

**Issue by minhng99** [openwisp/openwisp-firmware-upgrader#127]
Hi, I'm getting these warning in the log after running for a while:
`
[WARNING 2021-03-11 11:55:14,460] module: base, process: 1329847, thread: 140595094034240
view's FirmwareImageDetailView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_firmware_upgrader/api/views.py", line 159, in get_queryset
    return super().get_queryset().filter(build=self.kwargs['build_pk'])
KeyError: 'build_pk'

[WARNING 2021-03-11 11:57:07,047] module: base, process: 1329845, thread: 140595094034240
view's NotificationReadAllView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'NotificationReadAllView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.

[WARNING 2021-03-11 11:57:07,070] module: base, process: 1329845, thread: 140595094034240
view's NotificationReadRedirect raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/opt/openwisp2/env/lib/python3.8/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'NotificationReadRedirect' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
`
OS: Ubuntu 20.04.2

**Comment by eleensmathew** [comment]
Hi can i work on this? I don't have experience working on a project like this so please guide me.

**Comment by SonakshiChauhan** [comment]
Hi I would like to work on this durinh hacktober fest. Please assign it to me @minhng99

**Comment by Vihar214** [comment]
Hello, Is there anyone working on this issue if not then can you assign this issue to Me?

**Comment by KumarADITHYA123** [comment]
Hi! I am a beginner and would love to work on this issue as my first contribution to OpenWISP. I have set up the project and will follow the suggested approach to fix the schema generation issue. Please let me know if I can work on this. Thank you!

**Comment by nemesifier** [comment]
The only remaining warning I see is the following:

```
/python3.10/site-packages/django_filters/rest_framework/backends.py:142:
UserWarning: <class 'openwisp_firmware_upgrader.api.views.DeviceUpgradeOperationListView'>
is not compatible with schema generation
  warnings.warn(
```

**Comment by pranshustuff** [comment]
I didn't get the above warning when I ran it. Seems fine to me.
