### ISSUE TITLE
[bug] FileNotFoundError when trying to delete an image which links a non existing file

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-firmware-upgrader#140]
This happens mostly during testing, but may happen during migrations as well.

How to replicate:

- create a firmware build and upload an image
- delete the image from the filesystem (not from openwisp)
- delete the image from openwisp

Result:

```
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/openwisp-firmware-upgrader/openwisp_firmware_upgrader/admin.py", line 159, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "/lib/python3.8/site-packages/django_reversion-3.0.7-py3.8.egg/reversion/admin.py", line 154, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1579, in _changeform_view
    if all_valid(formsets) and form_validated:
  File "/lib/python3.8/site-packages/django/forms/formsets.py", line 464, in all_valid
    valid &= formset.is_valid()
  File "/lib/python3.8/site-packages/django/forms/formsets.py", line 308, in is_valid
    self.errors
  File "/lib/python3.8/site-packages/django/forms/formsets.py", line 288, in errors
    self.full_clean()
  File "/lib/python3.8/site-packages/django/forms/formsets.py", line 336, in full_clean
    form_errors = form.errors
  File "/lib/python3.8/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/lib/python3.8/site-packages/django/forms/forms.py", line 376, in full_clean
    self._post_clean()
  File "/lib/python3.8/site-packages/django/forms/models.py", line 405, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/lib/python3.8/site-packages/django/db/models/base.py", line 1209, in full_clean
    self.clean_fields(exclude=exclude)
  File "/lib/python3.8/site-packages/django/db/models/base.py", line 1251, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/lib/python3.8/site-packages/django_private_storage-2.2.2-py3.8.egg/private_storage/fields.py", line 55, in clean
    file = data.file
  File "/lib/python3.8/site-packages/django/db/models/fields/files.py", line 43, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/lib/python3.8/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/lib/python3.8/site-packages/django/core/files/storage.py", line 231, in _open
    return File(open(self.path(name), mode))
```

Solution:

- catch the exception
- log it with logger.exception() (it's an exceptional situation which needs to be logged in case anyone wants to debug)
- avoid any other failure to ensure the FirmwareImage object gets deleted successfully from the DB

**Comment by prachipancholi** [comment]
Hey, can you brief me what is the issue to be fix?

**Comment by nemesisdesign** [comment]
> Hey, can you brief me what is the issue to be fix?

@prachipancholi what is it that is not clear in the issue description?

**Comment by hanif-ali** [comment]
I am working on this and have some doubts:
- Should we silently delete the `FirmwareImage` after logging the exception or keep it as it is?
- Instead of logging, we can also raise a ValidationError so that the user gets a message. What do you think of this approach?

**Comment by nickberry17** [comment]
> * Should we silently delete the `FirmwareImage` after logging the exception or keep it as it is?

If the user intended to delete the FirmwareImage in the first place then I'm +1 for automatically deleting it.

**Comment by AbhigyaShridhar** [comment]
Hey @nemesisdesign I think I can figure this one out! May I start working on it?

**Comment by nemesisdesign** [comment]
I think it would be obvious that the FirmwareImage would have to be deleted, I mean, the original intention of the user was to delete it, now there's an exception, if the exception is catched the flow will resume normally and the image will be deleted. I have upgraded the issue description to reflect that.

Anyone who wants to work on this, don't ask for permission, just send a PR!

**Comment by nemesisdesign** [comment]
It may be good to work on https://github.com/openwisp/openwisp-firmware-upgrader/issues/170 before working on this, because this issue may disappear automatically if https://github.com/openwisp/openwisp-firmware-upgrader/issues/170 is done.

**Comment by Vihar214** [comment]
Hello, Is there anyone working on this issue if not than can you assign this issue to Me.

**Comment by tspare** [comment]
I think this is fixed.  I could not reproduce this issue. This is my repo version:

commit 9c7840c7436eb8b8cd5a63e83194041ccf887cd2 (HEAD -> master, origin/master, origin/HEAD)
Author: Federico Capoano <f.capoano@openwisp.io>
Date:   Mon Jan 30 17:24:02 2023 -0300

**Comment by Ashish8329** [comment]
Hey @nemesifier , is this issue is open or need to fix?

**Comment by nemesifier** [comment]
@Ashish8329 I am not sure if this issue is still valid, testing if you can reproduce it would be useful.

**Comment by youhaveme9** [comment]
This issue is not valid anymore
We can close this

**Comment by nemesifier** [comment]
I confirm I can't replicate this on master. Thanks @youhaveme9.

**Comment by nemesifier** [comment]
I was able to replicate the error.

![Image](https://github.com/user-attachments/assets/010c53b6-a0a6-4d4b-9aed-db9df6b7b88d)

Stack trace:

```
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/nemesis/Code/openwisp/openwisp-firmware-upgrader/openwisp_firmware_upgrader/admin.py", line 230, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
    if all_valid(formsets) and form_validated:
  File "/lib/python3.10/site-packages/django/forms/formsets.py", line 579, in all_valid
    return all([formset.is_valid() for formset in formsets])
  File "/lib/python3.10/site-packages/django/forms/formsets.py", line 579, in <listcomp>
    return all([formset.is_valid() for formset in formsets])
  File "/lib/python3.10/site-packages/django/forms/formsets.py", line 384, in is_valid
    self.errors
  File "/lib/python3.10/site-packages/django/forms/formsets.py", line 366, in errors
    self.full_clean()
  File "/lib/python3.10/site-packages/django/forms/formsets.py", line 429, in full_clean
    form_errors = form.errors
  File "/lib/python3.10/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/lib/python3.10/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/lib/python3.10/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/lib/python3.10/site-packages/django/db/models/base.py", line 1470, in full_clean
    self.clean_fields(exclude=exclude)
  File "/lib/python3.10/site-packages/django/db/models/base.py", line 1522, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "/lib/python3.10/site-packages/private_storage/fields.py", line 46, in clean
    file = data.file
  File "/lib/python3.10/site-packages/django/db/models/fields/files.py", line 48, in _get_file
    self._file = self.storage.open(self.name, "rb")
  File "/lib/python3.10/site-packages/django/core/files/storage/base.py", line 22, in open
    return self._open(name, mode)
  File "/lib/python3.10/site-packages/django/core/files/storage/filesystem.py", line 68, in _open
    return File(open(self.path(name), mode))

Exception Type: FileNotFoundError at /admin/firmware_upgrader/build/8c9d32dd-f39b-41b6-8d9b-a0c226b15365/change/
```

This happens only if the specific firmware image is deleted, not the entire build (due to #301).

The error is also triggered if a new firmware image is added.
