### ISSUE TITLE
[bug] Deleting DeviceConnection object for a device with DeviceFirmareImage raises HTTP 500 error

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-firmware-upgrader#250]
**Steps to replicate**
1. Ensure that you have a celery worker running in the background
2. Create a device 
3. Add a credential to this device from the "Credentials" tab and save the form.
4. Add a firmware to this device from the "Firmware" tab and save the form. This step will create an UpgradeOperation for this device. Verify this from the "Upgrade Operations" tab. 
5. Delete the credentials from the "Credentials" tab and save the form.
6. Try saving the form again 

**Actual Outcome**

The application returns HTTP 500 response because of this error 

```text
Traceback (most recent call last):
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/openwisp_controller/config/admin.py", line 138, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/reversion/admin.py", line 162, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/openwisp_utils/admin.py", line 133, in change_view
    return super().change_view(
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
    if all_valid(formsets) and form_validated:
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/formsets.py", line 579, in all_valid
    return all([formset.is_valid() for formset in formsets])
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/formsets.py", line 579, in <listcomp>
    return all([formset.is_valid() for formset in formsets])
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/formsets.py", line 384, in is_valid
    self.errors
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/formsets.py", line 366, in errors
    self.full_clean()
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/formsets.py", line 429, in full_clean
    form_errors = form.errors
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/pandafy/openwisp/venv-firmware/lib/python3.8/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
  File "/home/pandafy/openwisp/openwisp-firmware-upgrader/openwisp_firmware_upgrader/base/models.py", line 69, in clean
    self.validate_upgrade_options()
  File "/home/pandafy/openwisp/openwisp-firmware-upgrader/openwisp_firmware_upgrader/base/models.py", line 56, in validate_upgrade_options
    if not getattr(self.upgrader_class, 'SCHEMA'):

Exception Type: AttributeError at /admin/config/device/e879d06b-672f-44c9-aa5e-561c56492663/change/
Exception Value: 'NoneType' object has no attribute 'SCHEMA'
```

**Comment by pandafy** [comment]
This is partially related to https://github.com/openwisp/openwisp-firmware-upgrader/issues/249

**Comment by youhaveme9** [comment]
Hey @pandafy I tried the steps and cannot replicate the error

Saving the form after deleting the credential and saving it redirects to Firmware tab with this message: 

![Image](https://github.com/user-attachments/assets/2b4ac253-225b-4286-a8b6-6e75177c3fe0)

> Celery worker running in the background

**Comment by pandafy** [comment]
@youhaveme9 perform two separate operations 
1. Add credentials to the device and save the form. 
2. Add a firmware to the device and save the form. 
3. Delete the credentials from the device and save the form. 
4. Change configuration of the device and save the form. 

You will observe an error in step 4.

**Comment by youhaveme9** [comment]
@pandafy 
I followed these steps 
```bash
Traceback (most recent call last):
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/openwisp_controller/config/admin.py", line 163, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/reversion/admin.py", line 162, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/openwisp_utils/admin.py", line 126, in change_view
    return super().change_view(
           
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
    if all_valid(formsets) and form_validated:
       ^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/formsets.py", line 579, in all_valid
    return all([formset.is_valid() for formset in formsets])
                ^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/formsets.py", line 384, in is_valid
    self.errors
    ^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/formsets.py", line 366, in errors
    self.full_clean()
    ^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/formsets.py", line 429, in full_clean
    form_errors = form.errors
                  ^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
    ^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
    ^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/env/lib/python3.12/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
    ^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/openwisp_firmware_upgrader/base/models.py", line 69, in clean
    self.validate_upgrade_options()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/openwisp_firmware_upgrader/base/models.py", line 56, in validate_upgrade_options
    if not getattr(self.upgrader_class, 'SCHEMA'):
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/openwisp_firmware_upgrader/base/models.py", line 706, in upgrader_class
    return get_upgrader_class_for_device(self.device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junexxd/PROGRAMMING/open-source/openwisp-firmware-upgrader/openwisp_firmware_upgrader/utils.py", line 32, in get_upgrader_class_for_device
    raise device.deviceconnection_set.model.DoesNotExist
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: DoesNotExist at /admin/config/device/b5374e70-f4c9-4110-b7af-44322beff5bb/change/
Exception Value: 
```

It triggered a different error

**Comment by pandafy** [comment]
@youhaveme9 the error stack trace has changed due to recent change.

**Comment by nemesifier** [comment]
I also bumped into this. We'll need to look closer into it.
I suggest to brainstorm possible solutions before trying to implement them.

**Comment by nemesifier** [comment]
Found a similar one here:
https://github.com/openwisp/openwisp-firmware-upgrader/issues/302
For that one it's clear to me what we should do.

On this one I am not 100% sure. The problem is that even if the user wants to fix the issue by assigning a credential object to the device, they won't be able to do so due to the logic in the firmware image complaining.

**Comment by komaleswarreddy** [comment]
Hi, I’d like to work on this issue.

I’m currently reproducing the problem locally and analyzing the validation flow around firmware images and device credentials before proposing a fix.

I’ll share findings or questions here before opening a PR.

**Comment by komaleswarreddy** [comment]
@nemesifier @pandafy Hi, I’m running into a persistent failure when running tests in parallel (coverage run runtests.py --parallel).

I’ve fixed the original issue (#250) and added regression tests, but the test suite still fails in parallel execution with:

multiprocessing.pool.MaybeEncodingError:
RecursionError: maximum recursion depth exceeded while pickling an object


I’ve already addressed the common causes:

removed lazy translations from ValidationError

ensured only plain strings/dicts are passed to ValidationError

updated tests to avoid retaining exception objects

replaced real ORM objects inside test exceptions with MagicMock

At this point, it seems related to Django’s parallel test runner pickling the full traceback for a failing test, rather than a single fixable validation path.

Could you please advise whether:

parallel execution is expected to work for this module, or

certain tests should be excluded from parallel runs, or

there is an established pattern in OpenWISP for handling this?

**Comment by komaleswarreddy** [comment]
@pandafy Thanks for checking and for the feedback.

You’re right — there are unrelated changes in the current PR that shouldn’t be there. I’ll clean up the branch and remove the openwisp-notifications and project settings changes so the diff only contains the firmware upgrader fix and related regression tests.

I’ll update the PR shortly with a minimal diff focused solely on this issue.
